version: '3.1'
 
services:
  db:
    image: mysql:8.0.20
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hola1234
      MYSQL_DATABASE: incidencias
      MYSQL_USER: incidencias
      MYSQL_PASSWORD: Hola1234
    ports:
      - "3306:3306"
    volumes:
      - ./incidencias.sql:/docker-entrypoint-initdb.d/incidencias.sql